language: node_js
version: 1.0
node_js:
  - "18"
cache:
  yarn: true
  directories:
    - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: "epam"
  ssh_known_hosts:
    - "$DEPLOY_SERVER"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 3.1.1
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /tmp/cc-test-reporter
  - chmod +x /tmp/cc-test-reporter
script:
  - yarn build
after_success:
  - mkdir coverage
  # merge coverage report from miew, miew-app projects
  - cat packages/miew-app/coverage/lcov.info | sed "s/^SF:src/SF:packages\\/miew-app\\/src/g" > coverage/lcov_miew-app.info
  - cat packages/miew/coverage/lcov.info | sed "s/^SF:src/SF:packages\\/miew\\/src/g" > coverage/lcov_miew.info
  - yarn run merge-cover
  # upload report to online quality tools
  - sonar-scanner
  - yarn run coveralls
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      /tmp/cc-test-reporter format-coverage -d -t lcov -o coverage/coverage.json coverage/general.info;
      /tmp/cc-test-reporter upload-coverage -i coverage/coverage.json;
    fi
  #- cp -r coverage/* packages/miew/build #to control results in deployed directory
deploy:
  - provider: npm
    edge: true
    cleanup: false
    email: "$NPM_EMAIL"
    api_key: "$NPM_AUTH_TOKEN"
    tag: latest
    on:
      tags: true
      node: "18"
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
  - provider: script
    edge: true
    cleanup: false
    script: "chmod +x ./tools/deploy.sh && ./tools/deploy.sh"
    on:
      all_branches: true
      node: "18"
notifications:
  slack:
    secure: CkwGMCqK7Liq81tnr7wMUJ893JW09caDeio5oOYQmjGwu3FBkwNU7zApRltN6NJ/a14Of97fHre0vMPga7BrNmhDH9ztvh6qafEmZXPYxiZSbOQ5JGYP3SlotIFF+z0WowCt6erXmNeRHzTBCoZKo4Sxd/2ZHLrkm3nVcCnugpIlyiFrhGnv+QIS2JbMVhai/0rYU1+CsIm6Lb/Kt4cpUgbdJGOsUizTZNKHxhgbnElFczaF0bUFbifkP7LRqdEXtsJPodLfPOezKM62BA6rBnlFGPrRKER1r3ZCHOHimAjyIWD6emUc331w2OmhXDuHGL4ZXq94joiHJVhfrnUsIzgewIxE0qKCMO7y4WcAdXCiwY+x1SoOUlUreJp6EkDI0IgiKOCfb8BnjSXV7VhqymGPjuvFvNzBxXyLjo9jceathGsKQ7usFjhVT1JBkmNYadVN8Y7PYEbyzOjWJol/f5Ol4B28pzypVMP3N6M0KKLJZ4gp6vFtobC72u7/7ThCfUfjDaPyf/yoUNmMQN6lLTRGvZnix+NU/DWVptbDrfAOm9+bBN7Z53Kdhfhpzjedr1Bb7Y+UuHSbNbQe0AvZdhzX3qCrneKDmlbIUvJfe1yzVh8981RedBFTXFcAb38wVfofnMrbZPaWw9k9L3fP1V52GYGjN6L2AX0VQZ3/arE=
    on_success: change
